Use item for hubris and virtue
Detailing-the-Realm/svnsea2e pull request #49
Opened 2021-11-30 15:38 UTC by Armaklan

The goal of this PR is to use "item" for Virtue and Hubris.

![image](https://user-images.githubusercontent.com/2310432/144078167-baa4a39d-c69c-4578-a7e7-8b99d231807c.png)

![image](https://user-images.githubusercontent.com/2310432/144078244-e7ee9d32-f120-4193-9250-3039366eb608.png)

Lack of specific icon for this items...

2021-11-30 20:19 UTC, mattraykowski requested changes

2021-11-30 20:19 UTC, mattraykowski commented on module/item/item.js
> +    console.log(data);
Probably don't need this anymore.

2021-12-01 07:29 UTC, Armaklan commented
I think i need add a migration process ( but I have to understand how it works before )

2021-12-01 07:33 UTC, Armaklan commented on module/item/item.js
> +    console.log(data);
Fix it

2021-12-01 14:47 UTC, mattraykowski approved these changes

2021-12-01 14:48 UTC, merged